package vehicles;

import java.awt.*;

/**
 *
 * @author sophiaanderson Feb 22, 2018 3:03:15 PM
 */
public class VFramePanel extends javax.swing.JPanel {

    Controller theController;
    int state = 0;
    int choice;
    private int NOTHING = 0;
    private int ADDING_SOURCE = 1;
    private int ADDING_VEHICLE = 2;

    public VFramePanel() {
        initComponents();
        reset();
    }

    public void reset() {
        theController = new Controller(this);
        setSize(1500, 1500);
        theController.start();
        setOptions();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        theController.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stepButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        intensitySlider = new javax.swing.JSlider();
        doneButton = new javax.swing.JButton();
        intensityLabel = new javax.swing.JLabel();
        agroVehicle = new javax.swing.JButton();
        fearVehicle = new javax.swing.JButton();
        loveVehicle = new javax.swing.JButton();
        explorerVehicle = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        delaySlider = new javax.swing.JSlider();
        delayLabel = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        stepButton.setText("Step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });
        add(stepButton);
        stepButton.setBounds(10, 10, 80, 29);

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        add(runButton);
        runButton.setBounds(10, 40, 80, 29);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(10, 70, 80, 29);

        intensitySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intensitySliderStateChanged(evt);
            }
        });
        add(intensitySlider);
        intensitySlider.setBounds(130, 70, 180, 29);

        doneButton.setText("Done");
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                doneButtonMousePressed(evt);
            }
        });
        add(doneButton);
        doneButton.setBounds(330, 50, 77, 29);

        intensityLabel.setText("Intensity");
        add(intensityLabel);
        intensityLabel.setBounds(190, 50, 60, 16);

        agroVehicle.setText("Aggression");
        agroVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agroVehicleActionPerformed(evt);
            }
        });
        add(agroVehicle);
        agroVehicle.setBounds(110, 50, 110, 29);

        fearVehicle.setText("Fear");
        fearVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fearVehicleActionPerformed(evt);
            }
        });
        add(fearVehicle);
        fearVehicle.setBounds(110, 80, 110, 29);

        loveVehicle.setText("Love");
        loveVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loveVehicleActionPerformed(evt);
            }
        });
        add(loveVehicle);
        loveVehicle.setBounds(220, 50, 110, 29);

        explorerVehicle.setText("Explorer");
        explorerVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explorerVehicleActionPerformed(evt);
            }
        });
        add(explorerVehicle);
        explorerVehicle.setBounds(220, 80, 110, 29);

        clearButton.setText("Clear All");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        add(clearButton);
        clearButton.setBounds(10, 100, 80, 29);

        delaySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                delaySliderStateChanged(evt);
            }
        });
        add(delaySlider);
        delaySlider.setBounds(170, 10, 190, 29);

        delayLabel.setText("Delay");
        add(delayLabel);
        delayLabel.setBounds(120, 20, 35, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        theController.incSteps();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        for (int i = 0; i < 10000; i++) {
            theController.incSteps();
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        reset();
        repaint();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        switch (state) {
            case 0:
                break;
            case 1:
                theController.theWorld.sourceClick(evt.getX(), evt.getY());
                repaint();
                break;
            case 2:
                theController.theWorld.vehicleClick(evt.getX(), evt.getY(), Math.random() * (2 * Math.PI), choice);
                repaint();
                break;
        }
    }//GEN-LAST:event_formMousePressed

    private void intensitySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intensitySliderStateChanged
        theController.theWorld.setIntensity(intensitySlider.getValue());
        System.out.println("" + intensitySlider.getValue());
    }//GEN-LAST:event_intensitySliderStateChanged

    private void doneButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMousePressed
        removeVOptions();
        removeSOptions();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        state = NOTHING;
    }//GEN-LAST:event_doneButtonMousePressed

    private void explorerVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorerVehicleActionPerformed
        choice = 3;
    }//GEN-LAST:event_explorerVehicleActionPerformed

    private void agroVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agroVehicleActionPerformed
        choice = 1;
    }//GEN-LAST:event_agroVehicleActionPerformed

    private void fearVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fearVehicleActionPerformed
        choice = 0;
    }//GEN-LAST:event_fearVehicleActionPerformed

    private void loveVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loveVehicleActionPerformed
        choice = 2;
    }//GEN-LAST:event_loveVehicleActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        theController.theWorld.theSourceList.clear();
        theController.theWorld.theVehicleList.clear();
        repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void delaySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_delaySliderStateChanged
        theController.setDelay(delaySlider.getValue());
    }//GEN-LAST:event_delaySliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agroVehicle;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel delayLabel;
    private javax.swing.JSlider delaySlider;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton explorerVehicle;
    private javax.swing.JButton fearVehicle;
    private javax.swing.JLabel intensityLabel;
    private javax.swing.JSlider intensitySlider;
    private javax.swing.JButton loveVehicle;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton runButton;
    private javax.swing.JButton stepButton;
    // End of variables declaration//GEN-END:variables

    void addSourceSelected() {
        state = ADDING_SOURCE;
    }

    void addSOptions() {
        intensitySlider.setVisible(true);
        intensityLabel.setVisible(true);
        doneButton.setVisible(true);

    }

    void addVehicleSelected() {
        state = ADDING_VEHICLE;
    }

    void addVOptions() { ///***********
        doneButton.setVisible(true);
        loveVehicle.setVisible(true);
        fearVehicle.setVisible(true);
        explorerVehicle.setVisible(true);
        agroVehicle.setVisible(true);

    }

    void removeVOptions() {
        doneButton.setVisible(false);
        loveVehicle.setVisible(false);
        fearVehicle.setVisible(false);
        explorerVehicle.setVisible(false);
        agroVehicle.setVisible(false);

    }

    void removeSOptions() { ///***********
        doneButton.setVisible(false);
        intensitySlider.setVisible(false);
        intensityLabel.setVisible(false);
    }

    private void setOptions() {
        intensitySlider.setMinimum(10);
        intensitySlider.setMaximum(200000);
        intensitySlider.setMinorTickSpacing(20000);
        intensitySlider.setPaintTicks(true);
        
        delaySlider.setMinimum(10);
        delaySlider.setMaximum(200);
        delaySlider.setMinorTickSpacing(10);
        delaySlider.setPaintTicks(true);

        doneButton.setVisible(false);
        intensitySlider.setVisible(false);
        intensityLabel.setVisible(false);

        loveVehicle.setVisible(false);
        fearVehicle.setVisible(false);
        explorerVehicle.setVisible(false);
        agroVehicle.setVisible(false);

        state = NOTHING;
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

    }

}
