/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab0a;

/**
 *
 * @author sophiaanderson
 */
public class Lab0aFrame extends javax.swing.JFrame {

    private DisplayFrame otherFrame;

    /**
     * Creates new form Lab0aFrame
     */
    public Lab0aFrame() {
        initComponents();
        fillbox();
        makeTheOtherFrame();
        setTitle("Lab0a");

        setSize(500, 500); //sets it to "this" without an object name
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        theComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        TextArea.setText("1 2 3 4\n\n\n5 6 7 6 5 4\n\n\n23   34   54 \t\t92\n2 1 2 4 5 6 1 0 1 0 1 0 0 100 ");
        jScrollPane1.setViewportView(TextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 260, 280);

        theComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        theComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(theComboBox);
        theComboBox.setBounds(290, 20, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void theComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theComboBoxActionPerformed

        System.out.println("in action performed");
        if (theComboBox.getSelectedItem() == null) {
            System.out.println("oops");
            return;
        }
        String s = (String) theComboBox.getSelectedItem();
        System.out.println("s = " + s);
        if (otherFrame == null) {
            return;
        }
        otherFrame.go(Integer.parseInt(s), TextArea.getText());
    }//GEN-LAST:event_theComboBoxActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab0aFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> theComboBox;
    // End of variables declaration//GEN-END:variables

    private void fillbox() {
        theComboBox.removeAllItems();
        for (int i = 1; i < 10; i++) {
            theComboBox.addItem("" + i);
        }
    }

    private void makeTheOtherFrame() {
        otherFrame = new DisplayFrame();
    }
}
