package lab.pkg3.pendulum;

import java.awt.*;

/**
 *
 * @author sophiaanderson Feb 13, 2018 2:35:31 PM
 */
public class View extends javax.swing.JPanel {
    
    Controller theController;
    private final int number = 5;
    int left, right, range;
    double angle;
     

    public View() {
        initComponents();
        reset();
    }
    
    public void reset() {
        theController = new Controller(this);
        
        left = 150;
        right = 450;
        range = right-left;

        
        for (int i = 0; i<number; i++)
        {
            angle = 0.0;
            if(i+1==number)
            {
                angle = 0.5;
            }
            theController.addPend(new Pendulum(left+(i*range)/number, 100, angle, 0, 300));
        }

        theController.start();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        theController.paint(g);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(null);

        goButton.setText("Go!");
        goButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goButtonMousePressed(evt);
            }
        });
        add(goButton);
        goButton.setBounds(130, 10, 75, 29);

        resetButton.setText("Reset!");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetButtonMousePressed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(320, 10, 80, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goButtonMousePressed
        System.out.println("button????");
        theController.toggleRunning();
    }//GEN-LAST:event_goButtonMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        int mouseX = evt.getX();
        int mouseY = evt.getY();
        System.out.println("x,y = " + mouseX + " " + mouseY);
        theController.selectPendulum(mouseX, mouseY);
        repaint();
        //theController.addPend(new Pendulum(300,200,mouseX, mouseY));
        //repaint();
    }//GEN-LAST:event_formMousePressed

    private void resetButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMousePressed
        reset();
        repaint();
    }//GEN-LAST:event_resetButtonMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int mouseX = evt.getX();
        int mouseY = evt.getY();
        theController.dragPend(mouseX, mouseY);
        repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        theController.mouseup();
        repaint();
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

}
